#!/usr/bin/env python3
"""Validate String Catalogs and generate typed Swift message accessors."""
import argparse
import json
from pathlib import Path
import sys
sys.dont_write_bytecode = True
from lib.localization import check_source_literals, check_bundle, shipping_languages
from lib.localization_catalog import (read_catalogs, CLI_LANGUAGES, SHIP_THRESHOLD, REQUIRED_COMPLETE,
                                      validate_policy, check_completeness, accept_translations, coverage, read_baseline)

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'Sources/RuriLocalization/Generated'


def quoted(value):
    return json.dumps(value, ensure_ascii=False)


def documentation(value, table, key):
    # Keep the source text visible in code completion and Quick Help without
    # asking callers to duplicate it in source comments.
    lines = [('        /// ' + line).rstrip() for line in value.replace('%%', '%').splitlines()]
    lines += ['        ///', f'        /// Resource: `{table}.{key}`.']
    return lines


def run(check=False, format_files=False):
    check_source_literals(ROOT)
    catalogs = read_catalogs(ROOT, check_format=check, format_files=format_files)
    status = validate_policy(ROOT, catalogs)
    check_completeness(catalogs, status)
    groups = {}
    for item in catalogs.values():
        groups.setdefault(item['group'], []).append((item['name'], item['kinds'], item['key'], item['value'], item['table']))
    expected = {}
    for group, items in groups.items():
        lines = ['// Generated by scripts/localization.py. Edit the resource files instead.', 'import Foundation', '', 'extension Messages {', f'    public enum {group} {{']
        for name, kinds, key, value, table in items:
            lines += documentation(value, table, key)
            if not kinds:
                lines += [f'        public static var {name}: LocalizedMessage {{', f'            .init(key: {quoted(key)}, table: {quoted(table)}, fallback: {quoted(value)})', '        }']
            else:
                types = {'text': 'String', 'integer': 'Int64', 'decimal': 'Double'}
                args = ', '.join(f'_ value{i}: {types[kind]}' for i, kind in enumerate(kinds))
                values = ', '.join(f'.{kind}(value{i})' for i, kind in enumerate(kinds))
                lines += [f'        public static func {name}({args}) -> LocalizedMessage {{', f'            .init(key: {quoted(key)}, table: {quoted(table)}, fallback: {quoted(value)}, arguments: [{values}])', '        }']
        lines.append('        static let definitions: [String: MessageDefinition] = [')
        for name, kinds, key, value, table in items:
            args = ', '.join('.' + kind for kind in kinds)
            lines.append(f'            {quoted(table + ":" + key)}: .init({quoted(value)}, [{args}]),')
        lines += ['        ]', '    }', '}', '']
        expected[group + '.swift'] = '\n'.join(lines)
    lines = ['// Generated by scripts/localization.py. Edit the resource files instead.', 'public enum Messages {}', '', 'enum MessageCatalog {', '    static let definitions: [String: MessageDefinition] = {', '        var result: [String: MessageDefinition] = [:]']
    for group in sorted(groups):
        lines.append(f'        result.merge(Messages.{group}.definitions) {{ first, _ in first }}')
    lines += ['        return result', '    }()', '}', '']
    expected['MessageCatalog.swift'] = '\n'.join(lines)
    expected['SupportedLocalizations.swift'] = '// Generated by scripts/localization.py.\nenum SupportedLocalizations {\n    static let languages = [' + ', '.join(quoted(language) for language in shipping_languages(ROOT, catalogs, status)) + ']\n    static let commandLineLanguages = [' + ', '.join(quoted(language) for language in CLI_LANGUAGES) + ']\n}\n'
    stale = []
    for name, text in expected.items():
        path = OUTPUT / name
        if not path.exists() or path.read_text() != text:
            if check: stale.append(str(path.relative_to(ROOT)))
            else: path.write_text(text)
    for path in OUTPUT.glob('*.swift'):
        if path.name not in expected:
            if check: stale.append(str(path.relative_to(ROOT)))
            else: path.unlink()
    if stale:
        raise ValueError('Generated code is stale. Run scripts/localization.py:\n' + '\n'.join(stale))
    print(f'Localization: {len(catalogs)} messages, {len(groups)} accessor groups, resources valid. ' + coverage_summary(status))


def coverage_summary(status):
    return '; '.join(f"{language} {row['coverage']:.1%} ({len(row['missing'])} missing, {len(row['stale'])} stale)" for language, row in status.items())


def show_status(language=None):
    catalogs = read_catalogs(ROOT)
    status = validate_policy(ROOT, catalogs)
    if language and language not in status:
        raise ValueError('Unknown translation language: ' + language)
    print(coverage_summary({language: status[language]} if language else status))
    if language:
        for state in ['missing', 'stale']:
            for key in status[language][state]:
                print(f"{state}: {key} — {catalogs[key]['value']}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--format', action='store_true', help='Normalize String Catalog formatting')
    mode.add_argument('--status', nargs='?', const='', metavar='LANG', help='Show translation coverage and outdated source text')
    mode.add_argument('--accept', metavar='LANG', help='Accept existing translations against current source text')
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument('--keys', help='Comma-separated Group.name or Table:Group.name keys to accept')
    selection.add_argument('--all', action='store_true', help='Accept every existing translation')
    mode.add_argument('--bundle', type=Path, help='Verify resources in a built app after relocation')
    parser.add_argument('--cli', type=Path, help='Also verify a standalone CLI with --bundle')
    options = parser.parse_args()
    if options.cli and not options.bundle:
        parser.error('--cli requires --bundle')
    if (options.keys is not None or options.all) and not options.accept:
        parser.error('--keys and --all require --accept')
    if options.accept and not (options.keys or options.all):
        parser.error('--accept requires --keys or --all')
    try:
        if options.bundle:
            check_bundle(options.bundle.resolve(), options.cli.resolve() if options.cli else None)
        elif options.status is not None:
            show_status(options.status or None)
        elif options.accept:
            catalogs = read_catalogs(ROOT)
            validate_policy(ROOT, catalogs)
            count = accept_translations(ROOT, catalogs, options.accept,
                                        keys=[key.strip() for key in options.keys.split(',')] if options.keys else None, accept_all=options.all)
            print(f'Accepted {count} {options.accept} translations.')
            run()
        else:
            run(options.check, options.format)
    except (ValueError, KeyError, OSError) as error:
        sys.exit(str(error))
